# Built with Jekyll 3.6.0

# Setup
title:               Nos Cambio la Vida / Our Lives Transformed
tagline:             'draft'
description:         'Nos Cambio la Vida is a digital edition of short autobiographical narratives written by Dominican writers of Haitian descent that have 			 been translated into English.'
url:                 'https://github.com/dhc-barnard/nos-cambio-la-vida.git'
baseurl:             ''

# About/contact
author:
  name:              Barnard DHC
  url:               digitalhumanities.barnard.edu
  email:             apeaker@barnard.edu

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# gem specs
plugins:
  - jekyll-pdf

# front-matter defaults
defaults:
  -
    scope:
      path: ""
      type: "narratives"
    values:
      pdf: true
      pdf_layout: pdf.html

# Exclusions from the final site
exclude:
  - optional
  - vendor
  - ed..gemspec
  - Gemfile
  - Gemfile.lock
  - backstop_data
  - backstop.json

# Theme
# (Used for local or custom-server deployments)
# Uncomment the `theme` line if using the Ed. theme gem on your own computer or server.
# See https://jekyllrb.com/docs/themes/
# theme: "ed."

# Remote Theme
# (Used only for GitHub deployments)
# See https://help.github.com/en/articles/adding-a-jekyll-theme-to-your-github-pages-site
remote_theme: minicomp/ed
